name: 'Is Actor Authorized'

description: 'This action will determine if the actor who initiated the workflow is authorized to do so.'

inputs:
  actor: 
    description: 'The actor who initiated the workflow'
    required: true
  authorized-actors:
    description: 'An array of strings containing the authorized github usernames'
    required: true
  
runs:
  using: 'node20'
  main: 'dist/index.js'
